version: '3.9'
services:
  app:
    container_name: md-app
    build:
      context: .devcontainer
      args:
        - WORKDIR=workspace
    init: true
    tty: true
    volumes:
      - ./:/workspace
      - ../.ssh:/root/.ssh
      - ../.zshrc:/root/.zshrc
      - ../.p10k.zsh:/root/.p10k.zsh
